/**
 * Central route registry. Import from here instead of hardcoding paths so
 * refactors touch a single file.
 */
export const ROUTES = {
  root: "/",
  marketing: {
    about: "/about",
    courses: "/courses",
    faculty: "/faculty",
    achievements: "/achievements",
    demo: "/demo",
    contact: "/contact",
  },
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    forgotPassword: "/auth/forgot-password",
  },
  app: {
    root: "/app",
    dashboard: "/app/dashboard",
    settings: "/app/settings",
    courses: "/app/courses",
    course: "/app/courses/:courseId",
    attendance: "/app/attendance",
    tests: "/app/tests",
    test: "/app/tests/:testId",
    fees: "/app/fees",
    notifications: "/app/notifications",
    profile: "/app/profile",
    bookmarks: "/app/bookmarks",
    homework: "/app/homework",
    assignments: "/app/assignments",
    students: "/app/students",
    reports: "/app/reports",
    analytics: "/app/analytics",
    messages: "/app/messages",
  },
  admin: {
    root: "/admin",
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    settings: "/admin/settings",
    students: "/admin/students",
    teachers: "/admin/teachers",
    parents: "/admin/parents",
    batches: "/admin/batches",
    courses: "/admin/courses",
    revenue: "/admin/revenue",
    fees: "/admin/fees",
    notifications: "/admin/notifications",
    analytics: "/admin/analytics",
    reports: "/admin/reports",
  },
  errors: {
    notFound: "/404",
    unauthorized: "/403",
    sessionExpired: "/session-expired",
  },
} as const;
