import type { Question, Test } from "@/types/cbt";

export const SAMPLE_TESTS: Test[] = [
  {
    id: "test-1",
    title: "JEE Mock Test #8 — Physics",
    description: "Full-length physics mock test covering Mechanics, Thermodynamics, and Waves.",
    subject: "Physics",
    durationMinutes: 180,
    totalMarks: 100,
    negativeMarking: true,
    randomQuestions: true,
    status: "published",
    startDate: "2025-07-20T10:00",
    endDate: "2025-07-20T13:00",
    createdAt: "2025-07-10",
    updatedAt: "2025-07-10",
  },
  {
    id: "test-2",
    title: "Chemistry Unit Test — Organic",
    description: "Test your knowledge of organic chemistry reactions and mechanisms.",
    subject: "Chemistry",
    durationMinutes: 60,
    totalMarks: 50,
    negativeMarking: false,
    randomQuestions: false,
    status: "published",
    startDate: "2025-07-22T14:00",
    endDate: "2025-07-22T15:00",
    createdAt: "2025-07-12",
    updatedAt: "2025-07-12",
  },
  {
    id: "test-3",
    title: "Math Speed Test — Calculus",
    description: "Quick-fire calculus problems. 45 minutes, 30 questions.",
    subject: "Mathematics",
    durationMinutes: 45,
    totalMarks: 60,
    negativeMarking: true,
    randomQuestions: true,
    status: "published",
    startDate: "2025-07-25T16:00",
    endDate: "2025-07-25T16:45",
    createdAt: "2025-07-14",
    updatedAt: "2025-07-14",
  },
];

export const SAMPLE_QUESTIONS: Record<string, Question[]> = {
  "test-1": [
    {
      id: "q1",
      testId: "test-1",
      type: "mcq",
      question: "A particle moves in a straight line with constant acceleration. If it covers 10 m in the first second and 20 m in the third second, what is its acceleration?",
      options: ["2.5 m/s²", "5 m/s²", "7.5 m/s²", "10 m/s²"],
      correctAnswer: "5 m/s²",
      explanation: "Using s_n = u + a(2n-1)/2, we get a = 5 m/s².",
      marks: 4,
      negativeMarks: 1,
      createdAt: "2025-07-10",
      updatedAt: "2025-07-10",
    },
    {
      id: "q2",
      testId: "test-1",
      type: "mcq",
      question: "The SI unit of thermal conductivity is:",
      options: ["W/m·K", "J/m·K", "W·m/K", "J·m/K"],
      correctAnswer: "W/m·K",
      explanation: "Thermal conductivity measures heat transfer rate per unit distance per unit temperature difference.",
      marks: 4,
      negativeMarks: 1,
      createdAt: "2025-07-10",
      updatedAt: "2025-07-10",
    },
    {
      id: "q3",
      testId: "test-1",
      type: "mcq",
      question: "A wave has frequency 500 Hz and speed 350 m/s. What is its wavelength?",
      options: ["0.5 m", "0.7 m", "1.4 m", "2.0 m"],
      correctAnswer: "0.7 m",
      explanation: "λ = v/f = 350/500 = 0.7 m.",
      marks: 4,
      negativeMarks: 1,
      createdAt: "2025-07-10",
      updatedAt: "2025-07-10",
    },
    {
      id: "q4",
      testId: "test-1",
      type: "subjective",
      question: "Derive the equation of motion for a particle undergoing simple harmonic motion and explain the physical significance of each term.",
      marks: 10,
      negativeMarks: 0,
      createdAt: "2025-07-10",
      updatedAt: "2025-07-10",
    },
  ],
  "test-2": [
    {
      id: "q5",
      testId: "test-2",
      type: "mcq",
      question: "Which of the following is the most stable carbocation?",
      options: ["Methyl", "Primary", "Secondary", "Tertiary"],
      correctAnswer: "Tertiary",
      explanation: "Tertiary carbocations are stabilized by hyperconjugation and inductive effects from three alkyl groups.",
      marks: 5,
      negativeMarks: 0,
      createdAt: "2025-07-12",
      updatedAt: "2025-07-12",
    },
    {
      id: "q6",
      testId: "test-2",
      type: "mcq",
      question: "The IUPAC name of CH₃CH₂CH(CH₃)₂ is:",
      options: ["2-methylbutane", "2-methylpropane", "3-methylbutane", "Isopentane"],
      correctAnswer: "2-methylbutane",
      explanation: "The longest chain has 4 carbons with a methyl group at position 2.",
      marks: 5,
      negativeMarks: 0,
      createdAt: "2025-07-12",
      updatedAt: "2025-07-12",
    },
  ],
  "test-3": [
    {
      id: "q7",
      testId: "test-3",
      type: "mcq",
      question: "What is the derivative of sin(x²)?",
      options: ["cos(x²)", "2x·cos(x²)", "2x·sin(x²)", "-cos(x²)"],
      correctAnswer: "2x·cos(x²)",
      explanation: "Using chain rule: d/dx[sin(x²)] = cos(x²) · 2x.",
      marks: 2,
      negativeMarks: 1,
      createdAt: "2025-07-14",
      updatedAt: "2025-07-14",
    },
  ],
};

export const SAMPLE_LEADERBOARD = [
  { studentUid: "u1", studentName: "Arjun Mehta", score: 92, totalMarks: 100, rank: 1, percentage: 92 },
  { studentUid: "u2", studentName: "Sneha Reddy", score: 88, totalMarks: 100, rank: 2, percentage: 88 },
  { studentUid: "u3", studentName: "Karan Patel", score: 85, totalMarks: 100, rank: 3, percentage: 85 },
  { studentUid: "u4", studentName: "Priya Singh", score: 78, totalMarks: 100, rank: 4, percentage: 78 },
  { studentUid: "u5", studentName: "Rahul Kumar", score: 75, totalMarks: 100, rank: 5, percentage: 75 },
];
